#!/usr/bin/env bash
# Common helpers for all nightshift hooks.
# Source this at the top of a hook script:
#   source "$(dirname "${BASH_SOURCE[0]}")/lib/common.sh"

# After v1.1 the plugin is SELF-CONTAINED: runtime lives inside the plugin
# itself at claude/bin/runtime/ (generated by
# scripts/prepare-claude-plugin-runtime.sh). Hooks resolve the runtime
# relative to their own file path, never via the repo root, so the plugin
# keeps working after Claude copies it into its cache dir.

# PLUGIN_ROOT is the claude/ directory containing .claude-plugin/plugin.json.
# common.sh lives at claude/hooks/lib/common.sh → two dirs up is claude/.
PLUGIN_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
export PLUGIN_ROOT

# RUNTIME_DIR holds the packaged core/ (event-store, scripts, schemas, etc).
# Allow NIGHTSHIFT_RUNTIME_DIR to override for dev-time experimentation.
NIGHTSHIFT_RUNTIME_DIR="${NIGHTSHIFT_RUNTIME_DIR:-$PLUGIN_ROOT/bin/runtime}"
export NIGHTSHIFT_RUNTIME_DIR

# Fail early and loudly if the runtime isn't packaged — prevents silent
# fallthrough to ns_allow in hooks.
if [ ! -d "$NIGHTSHIFT_RUNTIME_DIR" ]; then
  echo "nightshift: plugin runtime missing at $NIGHTSHIFT_RUNTIME_DIR" >&2
  echo "  Run: bash scripts/prepare-claude-plugin-runtime.sh (from the repo root)" >&2
  echo "  or reinstall the plugin." >&2
  exit 1
fi

# Read the hook event JSON from stdin into $HOOK_EVENT (once).
ns_read_event() {
  if [ -z "${HOOK_EVENT:-}" ]; then
    HOOK_EVENT="$(cat)"
    export HOOK_EVENT
  fi
  printf '%s' "$HOOK_EVENT"
}

# Extract a field from the hook event via node (jq may not be installed).
ns_event_field() {
  local path="$1"
  node -e '
    const p = process.argv[1].split(".");
    const e = JSON.parse(process.env.HOOK_EVENT || "{}");
    let cur = e;
    for (const k of p) { if (cur == null) break; cur = cur[k]; }
    if (cur == null) process.exit(0);
    process.stdout.write(typeof cur === "string" ? cur : JSON.stringify(cur));
  ' "$path"
}

# Get the project dir (cwd of the Claude Code session).
ns_project_dir() {
  ns_event_field cwd
}

# Return a valid nightshift-format session_id: the one from the hook event if
# it matches the schema, otherwise a freshly generated ULID.
ns_session_id() {
  local raw
  raw="$(ns_event_field session_id 2>/dev/null || true)"
  if [ -n "$raw" ] && echo "$raw" | grep -qE '^sess_[0-9A-HJKMNP-TV-Z]{20,40}$'; then
    printf '%s' "$raw"
  else
    node --input-type=module -e "import(process.argv[1]).then(m=>process.stdout.write(m.sessionId()))" \
      "$NIGHTSHIFT_RUNTIME_DIR/event-store/src/id.mjs" 2>/dev/null
  fi
}

# Append one event via the dispatch layer. The payload JSON may omit
# session_id; we inject a valid one before sending so audit lines survive
# even when the caller-supplied session_id was invalid.
# Usage: ns_append_event '{"agent":"system","action":"guard.violation",...}'
ns_append_event() {
  local payload="$1"
  local log
  log="$(ns_project_dir)/tasks/events.ndjson"
  if [ ! -d "$(dirname "$log")" ]; then
    return 0
  fi
  local sid
  sid="$(ns_session_id)"
  # Inject/overwrite session_id field in the payload JSON via node, then send.
  PAYLOAD="$payload" SID="$sid" node -e '
    const p = JSON.parse(process.env.PAYLOAD || "{}");
    p.session_id = process.env.SID;
    process.stdout.write(JSON.stringify(p));
  ' 2>/dev/null \
    | node "$NIGHTSHIFT_RUNTIME_DIR/scripts/dispatch.mjs" append --log "$log" >/dev/null 2>&1 \
    || true
}

# Decide "block" with a reason (Claude Code hook response).
ns_block() {
  local reason="$1"
  node -e '
    const r = process.argv[1];
    process.stdout.write(JSON.stringify({ decision: "block", reason: r }));
  ' "$reason"
  exit 2
}

# Allow (no-op; exit 0 also means allow).
ns_allow() {
  exit 0
}

# Most recently active task — one whose latest task.* event is NOT terminal.
# Terminal: accepted | rejected | revised | promoted_to_heavy.
# Active spans every other task.* lifecycle action (contracted, context_packed,
# routed, dispatched, blocked, resolved, implemented, reviewed).
# Echoes: "WAVE\tTASK_ID" (tab-separated) or empty if none.
ns_active_task() {
  local log
  log="$(ns_project_dir)/tasks/events.ndjson"
  [ -f "$log" ] || return 0
  node -e '
    const fs = require("fs");
    const log = process.argv[1];
    const lines = fs.readFileSync(log, "utf8").split("\n").filter(Boolean);
    const terminal = new Set([
      "task.accepted",
      "task.rejected",
      "task.revised",
      "task.promoted_to_heavy"
    ]);
    let best = null;
    for (const l of lines) {
      try {
        const e = JSON.parse(l);
        if (!e.task_id) continue;
        if (!e.action || !e.action.startsWith("task.")) continue;
        if (terminal.has(e.action)) {
          if (best && best.id === e.task_id) best = null;
          continue;
        }
        best = { id: e.task_id, wave: e.wave };
      } catch {}
    }
    if (best) process.stdout.write(`${best.wave}\t${best.id}`);
  ' "$log"
}

# Extract write targets from a Bash command string. Covers common patterns:
#   > path, >> path, tee path, sed -i path, mv src dst, cp src dst,
#   touch path, ln path, install -m mode src dst.
# Best-effort; returns one path per line.
ns_bash_write_targets() {
  local cmd="$1"
  [ -z "$cmd" ] && return 0
  CMD="$cmd" node -e '
    const s = process.env.CMD || "";
    const out = new Set();
    const patterns = [
      /(?<![|&>])\s*(?:>>?|[12]>>?)\s*([^\s|&;<>]+)/g,
      /\btee(?:\s+-\S+)*\s+([^\s|&;<>]+)/g,
      /\bsed\s+-i(?:\s*\S*)?(?:\s+-e\s+\S+)*\s+([^\s|&;<>]+)$/gm,
      /\b(?:mv|cp)(?:\s+-\S+)*\s+\S+\s+([^\s|&;<>]+)/g,
      /\btouch(?:\s+-\S+)*\s+([^\s|&;<>]+)/g,
      /\binstall(?:\s+-\S+)*(?:\s+\S+)*\s+([^\s|&;<>]+)$/gm,
      /\bln(?:\s+-\S+)*\s+\S+\s+([^\s|&;<>]+)/g
    ];
    for (const re of patterns) {
      let m;
      while ((m = re.exec(s)) !== null) {
        out.add(m[1].replace(/^["\x27]|["\x27]$/g, ""));
      }
    }
    for (const p of out) process.stdout.write(p + "\n");
  '
}

# Extract `allowed_files` list from a task contract (simple YAML parse via node).
ns_allowed_files() {
  local contract="$1"
  [ -f "$contract" ] || return 0
  node -e '
    const fs = require("fs");
    const t = fs.readFileSync(process.argv[1], "utf8");
    const m = t.match(/```yaml\s*\n([\s\S]*?)```/);
    if (!m) process.exit(0);
    const yaml = m[1];
    const lines = yaml.split(/\r?\n/);
    let inSection = false;
    const out = [];
    for (const ln of lines) {
      if (/^allowed_files:\s*$/.test(ln)) { inSection = true; continue; }
      if (inSection) {
        if (/^\s*-\s+/.test(ln)) out.push(ln.replace(/^\s*-\s+/, "").trim().replace(/^["\x27]|["\x27]$/g, ""));
        else if (/^[a-z_]+:/.test(ln)) break;
      }
    }
    process.stdout.write(out.join("\n"));
  ' "$contract"
}

# Match a file path against a glob list. Returns 0 if any matches, 1 otherwise.
ns_file_matches_any() {
  local path="$1"; shift
  local globs="$*"
  [ -z "$globs" ] && return 1
  node -e '
    const p = process.argv[1];
    const globs = process.argv.slice(2);
    function toRegex(g) {
      const esc = g.replace(/[.+^${}()|\\]/g, "\\$&");
      const re = esc
        .replace(/\*\*/g, "§§DOUBLESTAR§§")
        .replace(/\*/g, "[^/]*")
        .replace(/§§DOUBLESTAR§§/g, ".*")
        .replace(/\?/g, ".");
      return new RegExp("^" + re + "$");
    }
    for (const g of globs) if (toRegex(g).test(p)) process.exit(0);
    process.exit(1);
  ' "$path" $globs
}
