#!/usr/bin/env bash
# prepare-claude-plugin-runtime.sh — build a self-contained runtime
# inside claude/bin/runtime/ so the Claude plugin works after Claude Code
# copies it to its cache dir (no ../core / repo-relative references at
# plugin execution time).
#
# Deterministic: writes claude/bin/runtime/MANIFEST.json with
#   { version, generated_at, files: [{ path, sha256 }...] }
# so we can detect drift and verify integrity.
#
# Idempotent: re-runs rebuild the directory from scratch.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
runtime="$root/claude/bin/runtime"

# Bail if claude/ plugin layout is missing (sanity check — we must be
# inside the nightshift repo itself, not a target project).
if [ ! -d "$root/claude/.claude-plugin" ]; then
  echo "prepare-claude-plugin-runtime: $root does not look like the nightshift repo root (no claude/.claude-plugin/)" >&2
  exit 2
fi

echo "[prepare] runtime target: $runtime"

# ---------- 1. wipe and recreate layout ----------
rm -rf "$runtime"
mkdir -p "$runtime/event-store/src" "$runtime/schemas" "$runtime/scripts"

# ---------- 2. copy source files ----------
# event-store
cp -v "$root/core/event-store/src/id.mjs"         "$runtime/event-store/src/" >/dev/null
cp -v "$root/core/event-store/src/index.mjs"      "$runtime/event-store/src/" >/dev/null
cp -v "$root/core/event-store/src/projection.mjs" "$runtime/event-store/src/" >/dev/null
cp -v "$root/core/event-store/src/validator.mjs"  "$runtime/event-store/src/" >/dev/null

# schemas
cp -v "$root/core/schemas/event.schema.json"    "$runtime/schemas/" >/dev/null
cp -v "$root/core/schemas/state.schema.json"    "$runtime/schemas/" >/dev/null
cp -v "$root/core/schemas/contract.schema.json" "$runtime/schemas/" >/dev/null
cp -v "$root/core/schemas/manifest.schema.json" "$runtime/schemas/" >/dev/null
cp -v "$root/core/schemas/costs.json"           "$runtime/schemas/" >/dev/null

# scripts (mjs)
for f in dispatch.mjs replay-events.mjs compliance-reporter.mjs project-status.mjs \
         health-ping.mjs morning-digest.mjs wave-reviewer.mjs wave-review-consumer.mjs \
         post-sync-docs.mjs truth-score.mjs router.mjs provision.mjs infra-audit.mjs; do
  cp -v "$root/core/scripts/$f" "$runtime/scripts/" >/dev/null
done

# scripts (shell)
for f in worktree-manager.sh checkpoint-manager.sh preflight.sh run-with-secrets.sh snapshot.sh; do
  cp -v "$root/core/scripts/$f" "$runtime/scripts/" >/dev/null
done
chmod +x "$runtime/scripts/"*.sh "$runtime/scripts/"*.mjs 2>/dev/null || true

# secrets + provisioners (dispatch.mjs and provision.mjs need them)
mkdir -p "$runtime/secrets" "$runtime/provisioners"
cp -v "$root/core/secrets/interface.mjs"              "$runtime/secrets/" >/dev/null
cp -v "$root/core/secrets/local-folder-backend.mjs"   "$runtime/secrets/" >/dev/null
cp -v "$root/core/secrets/onepassword-backend.mjs"    "$runtime/secrets/" >/dev/null
cp -v "$root/core/secrets/index.mjs"                  "$runtime/secrets/" >/dev/null
cp -v "$root/core/provisioners/interface.mjs" "$runtime/provisioners/" >/dev/null
cp -v "$root/core/provisioners/vercel.mjs"    "$runtime/provisioners/" >/dev/null
cp -v "$root/core/provisioners/supabase.mjs"  "$runtime/provisioners/" >/dev/null
cp -v "$root/core/provisioners/railway.mjs"   "$runtime/provisioners/" >/dev/null
cp -v "$root/core/provisioners/redis.mjs"     "$runtime/provisioners/" >/dev/null
cp -v "$root/core/provisioners/index.mjs"     "$runtime/provisioners/" >/dev/null

# codex client (used by dispatch.mjs)
mkdir -p "$runtime/codex"
cp -v "$root/core/codex/client.mjs" "$runtime/codex/" >/dev/null

# ---------- 3. fix import paths ----------
# In-source imports like `'../../event-store/src/index.mjs'` (from scripts/*.mjs)
# resolve to `runtime/event-store/src/index.mjs`. The layout is identical so
# those imports stay correct. Secrets/provisioners/scripts cross-references
# keep working because we preserved relative paths.
#
# Nothing to rewrite. If a script needed absolute paths we'd handle here.

# ---------- 4. install runtime deps (ajv + ajv-formats) ----------
# Isolated node_modules for the runtime so the plugin is self-contained.
cat >"$runtime/package.json" <<'EOF'
{
  "name": "nightshift-plugin-runtime",
  "version": "1.1.0",
  "private": true,
  "type": "module",
  "description": "Self-contained runtime for the Claude Code plugin. Generated by scripts/prepare-claude-plugin-runtime.sh — do not hand-edit.",
  "dependencies": {
    "ajv": "^8.18.0",
    "ajv-formats": "^3.0.1"
  }
}
EOF

echo "[prepare] installing ajv + ajv-formats into runtime..."
(
  cd "$runtime"
  if command -v pnpm >/dev/null 2>&1; then
    pnpm install --prod --ignore-workspace --silent 2>/dev/null || pnpm install --prod --silent
  elif command -v npm >/dev/null 2>&1; then
    npm install --omit=dev --silent
  else
    echo "prepare-claude-plugin-runtime: neither pnpm nor npm found" >&2
    exit 3
  fi
) >/dev/null

# ---------- 5. build manifest (file list + sha256) ----------
echo "[prepare] building MANIFEST.json..."
node -e '
  const fs = require("fs");
  const path = require("path");
  const crypto = require("crypto");
  const root = process.argv[1];
  const files = [];
  function walk(dir, rel = "") {
    for (const name of fs.readdirSync(dir).sort()) {
      const full = path.join(dir, name);
      const r = rel ? path.join(rel, name) : name;
      const st = fs.statSync(full);
      if (st.isDirectory()) {
        // Skip node_modules (tracked separately via package.json lock).
        if (r === "node_modules") continue;
        walk(full, r);
      } else {
        const h = crypto.createHash("sha256").update(fs.readFileSync(full)).digest("hex");
        files.push({ path: r.replace(/\\/g, "/"), sha256: h, bytes: st.size });
      }
    }
  }
  walk(root);
  const manifest = {
    schema_version: 1,
    runtime_version: "1.1.0",
    generated_at: new Date().toISOString(),
    source_root: "core/",
    notes: "Regenerated by scripts/prepare-claude-plugin-runtime.sh. Do not hand-edit.",
    files
  };
  fs.writeFileSync(path.join(root, "MANIFEST.json"), JSON.stringify(manifest, null, 2) + "\n");
  process.stdout.write(`[prepare] MANIFEST.json contains ${files.length} files\n`);
' "$runtime"

# ---------- 6. sanity check: no upward path references in runtime ----------
if grep -RlE '(\.\./){3,}' "$runtime/event-store" "$runtime/scripts" "$runtime/secrets" "$runtime/provisioners" 2>/dev/null | grep -v MANIFEST.json; then
  echo "[prepare] WARNING: found deep upward relative paths in runtime — verify by hand" >&2
fi

echo "[prepare] done. Runtime at: $runtime"
echo "[prepare] size: $(du -sh "$runtime" | cut -f1)"
